name: Mirror Clang
on:
  workflow_dispatch:
    inputs:
      refs:
        description: 'Git refs (e.g., refs/head/main)'
        required: true
        default: refs/head/main
        type: string
      version:
        description: 'Clang version (e.g., r522817)'
        required: true
        default: r522817
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Mirror AOSP Clang
    runs-on: ubuntu-latest
    env:
      refs: ${{ github.event.inputs.refs }}
      version: ${{ github.event.inputs.version }}
    steps:
      - name: Prepare workspace
        run: mkdir -p ${{ github.workspace }}/clang

      - name: Download Clang archive
        run: |
          cd ${{ github.workspace }}/clang
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/${{ env.refs }}/clang-${{ env.version }}.tar.gz -O clang.tar.gz
          if [ ! -s clang.tar.gz ]; then
            echo "Download failed or empty file"
            exit 1
          fi

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: clang-${{ env.version }}-aosp
          name: AOSP Clang ${{ env.version }}
          files: ${{ github.workspace }}/clang/clang.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
